# -*- coding: utf-8 -*-
"""prediksi-rekomendasi.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iks-7F8KAEsxWUlhbJLXwYD4um5Q0Kns
"""

import streamlit as st
import pickle

# Load model
model1 = pickle.load(open('rf_modelPrice.sav', 'rb'))
model2 = pickle.load(open('rf_modelStock.sav', 'rb'))
model3 = pickle.load(open('rf_modelPopu.sav', 'rb'))

# Antarmuka Streamlit
def main():
    st.title("Sistem Rekomendasi Produk")
    st.markdown("""

    Aplikasi Analisis dan Rekomendasi Produk

    """, unsafe_allow_html=True)

    with st.form(key='my_form'):
        nama_produk = st.text_input("Nama Produk")
        kategori = st.selectbox("Pilih Kategori", categories)
        harga = st.number_input("Harga", min_value=0, step=1000)
        total_rating = st.number_input("Total Rating", min_value=0, step=1)
        min_terjual = total_rating if total_rating > 0 else 0
        terjual = st.number_input("Jumlah Terjual", min_value=min_terjual, step=1)
        stock = st.number_input("Stock", min_value=0, step=1)

        # Tombol submit form
        submit_button = st.form_submit_button(label="Proses Rekomendasi")

    # Logika setelah tombol diklik
    if submit_button:
        kategori_index = categories.index(kategori) + 1  # Konversi ke indeks kategori numerik
        data_input = {
            'nama_produk': [nama_produk],
            'kategori': [kategori_index],
            'harga': [harga],
            'total_rating': [total_rating],
            'terjual': [terjual],
            'stock': [stock]
        }
        df = pd.DataFrame(data_input)
        hasil = prediction(df)
        st.success("Berikut adalah hasil analisis produk:")
        st.dataframe(hasil)
    else:
        st.info("Isi form di atas dan tekan tombol 'Proses Rekomendasi' untuk melihat hasil analisis.")

if __name__ == '__main__':
    main()
